### ISSUE TITLE
Why to give access to Admin regarding username password modify of employees?

### ISSUE THREAD

**Issue by HASEENAFATHIMA786** [rkmighwal/Office-Management-System#1]
Admin provides username and password to the employee through which they can log in and use the system. He also has the right to add or modify the given username and password of the employee.
My view:
Admin can provide username and password to employees. What is the need for modify the username or password for employees. If the employees forget the password then employees should be given permission or any email verification to reset password on own. They should not depend on Admin for changing username or password in case of any cases forgot password.

**Comment by rkmighwal** [comment]
@HASEENAFATHIMA786, you are correct, forgot password should be there. In my view, there should be a business admin, which have rights for add users, username and password should be system generated, and on first login user should change password. 
        By the way, this was my side project for college, have not work much on this, if you want to continue on this, i can help.

**Comment by HASEENAFATHIMA786** [comment]
Hi @rkmighwal,
Yes I like to take up Office Management System and continue with the work.
Can you please help me. Please ping me when you saw message...

**Comment by rkmighwal** [comment]
Hi @haseenafathima,

Let me know how i can help. :)

**Comment by HASEENAFATHIMA786** [comment]
Hi Rohit,

Let me gothrough the project.

**Comment by HASEENAFATHIMA786** [comment]
Hi Rohit,

Let me gothrough the project.

**Comment by HASEENAFATHIMA786** [comment]
Hi @Rohit,
          Thank you for quick reply. Please can you provide personal
emailid to communicate.
My idea is there is no security in the existing system. I request admin
should not modify the employee password without his/her knowledge.
          Inorder to have security we can have as the employee password
should be in the encrypted form for admin. Admin can only reset to the
generic password of the employee and not modify the employee
password(already changed password by employee) given.Whenever the password
is changed warning message should be given to employee. When the employee
accepts password can be changed. Consider warning message is given through
employee personal email. Please can you provide further ideas. Please can
you suggest if there is any corrections in the idea suggests. :)

**Comment by rkmighwal** [comment]
Hi @HASEENAFATHIMA786,
Email ID : rkmighwal@gmail.com
Skype : live: rkmighwal (rkmighwal@live.com)

Regarding your idea, it will be very complicated for admin and employee both, if there is any approval process for password change. I think just a reset password email will be sufficient, for password change. While adding new user, an email should trigger by system with user's default credentials (like user name & system generated password), and while user login first time, system should force user to modify password. And when ever user want to change password, an email with password change link should trigger. It will be simple, rest think about if you like, my intimation is system should be simple for both admin and users.

**Comment by Ashok506** [comment]
Hi What is UserName and Password..?

**Comment by HASEENAFATHIMA786** [comment]
Hi @Ashok,
          We need usernameand Password for security reasons.
Initially when we get the computer from netwrok admin from the office a dummy username and password is set in system. The employee must change the usernameand password within week for security.

Hi @rkmighwal,
          Idea which you said is good. When a employee need to change the password each time a link is sent to mail makes the employee inconvenient because when an employee forget his/her password giving a verification link to email is not convenient according to me. Instead when password is reset by admin  we can send a verification code to employees. When the verification code is typed by the admin,he.she can reset the password. There is difference between reset password and changing password. The difference is reset the password is changing the password directly to dummy password in which after reset password the employee should change the password again for security. While reset the questions asked are enter employee id, enter new password to resets. Changing the password gives three options as enter old password, enter new password, confirm new password. The idea what I said is for reset password for employees.

**Comment by HASEENAFATHIMA786** [comment]
Hi @Rohit,
           Can you please say where exactly we have to update or do any
modification inorder to have password reset verification code.
As I have already said an idea as Whenever an employee wants reset
password, he/she approaches admin. When the admin reset the password, we
can send an verification code to employee mobile. The admin is allowed to
change the password of an employee only when he/she types the verification
code(sent as message to respective employee mobile) correct.
Will you please say if the approach is acceptable or not. Good if you give
any suggestions. Will you please say where exactly I have to do
alteration(module) to implement the above suggestions given by me. In
addition to the above request, will you please say what language to be used.

**Comment by rkmighwal** [comment]
@HASEENAFATHIMA786, Check /Account/Register handler under Account controller for that purpose.

**Comment by HASEENAFATHIMA786** [comment]
Hi @rkmighwal,
           In accountcontroller.cs the code for password change initially when the user register is given. There is no specific code for reset password. Why have yo closed the issue please can you clarify my doubts?
